# Generated by Django 5.2.3 on 2025-06-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actor",
            name="name",
        ),
        migrations.RemoveField(
            model_name="review",
            name="comment",
        ),
        migrations.AddField(
            model_name="actor",
            name="first_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="actor",
            name="last_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
